version: "3.7"
services:
  juliachan:
    build: .
    # change image name to your own if you want to push to dockerhub
    image: grasberg/juliachan:latest
    container_name: juliachan
    volumes:
      - ./db:/usr/src/app/db
